### ISSUE TITLE
Is it possible to save URL of bot message to LRS?

### ISSUE THREAD

**Issue by SandraSchufmann** [rwth-acis/las2peer-social-bot-manager-service#97]
For example, bitbot (TUD) and Feedbot (UL) return Feedback pdfs when a student uploads a student text. At the moment, the student texts are saved in our LRS. It would be great if the feedback could also be saved in the LRS, but that would take up too much space. Hence, the idea was to only save the url of the bot message in which the bot gave the Feedback. (https://chat.tech4comp.dbis.rwth-aachen.de/file-upload/...)
The bots are currently included in the Mentoring Workbench. There, students are also shown a progress bar with their uploaded texts. The purpose of the described feature would be to also include the Feedback texts in the progress bar, so that students don't have to scroll through the complete chat history to find their texts.
Is that possible in any way?

**Comment by Aran30** [comment]
Currently, the bots work in the following way: 

Student sends file to bot -> Social bot manager forwards file to tmitocar-service (http request) -> Tmitocar-service answers with file (http response) to bot manager service -> bot manager transforms received base64 encoded file and uploads it to chat channel. 

Note that the respone of the upload does not contain any information of the file-url. This means to find out about the url of the files, it would be neccessary to query every exchanged file in a conversation, or at the very least immediately query for the url after a file was uploaded. 

Now for storing the url in the LRS, there would be two possibilities: 

1. Either store all the url's in the LRS of every exchanged file (after uploading a file, immediately look up for the last sent file and store it in the LRS). 

2. Forward the url to the calling service (in our example tmitocar service), and let the service decide what to do with the URL. 

Unfortunately, for both cases I feel that more problems would arise: 

1. How does one decide in which LRS the statements are stored? Multiple bots will be active in the same rocket chat instance, yet with this method, only one lrs can be chosen, meaning that this method is too restrictive.
2. Restarting a connection to a service would create too much overhead in my opinion. 

What are your opinions on this? @AlexanderNeumann @lakhoune  @Taeuber-hub

**Comment by lakhoune** [comment]
I think option 2 seems like the most

**Comment by lakhoune** [comment]
When the bot manager calls [Post message](https://developer.rocket.chat/reference/api/rest-api/endpoints/team-collaboration-endpoints/chat-endpoints/postmessage), it returns the id of the chat message. So the message itself can then be retrieved using `api/v1/chat.getMessage?msgId=<id>`

To store the URL I think that the second option does make more sense since the service (e.g. tmitocar) is also the one that stores the text in the LRS.  We could adjust the bot manager service to send the message-id back to the service. Then the service (e.g. tmitocar) could do the LRS forwarding accordingly.

What bothers me more here is that we would need to adjust the bot manager service to handle a **specific** use case. I do not see how services in general could benefit from this feature...
